backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: public/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.md"
        fields:
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Subtitle", name: "subtitle", widget: "text"}
              - {label: "Hero Image", name: "image", widget: "image"}
              - {label: "CTA Button Text", name: "cta_text", widget: "string"}
          - label: "Features Section"
            name: "features"
            widget: "object"
            fields:
              - {label: "Section Title", name: "title", widget: "string"}
              - {label: "Section Description", name: "description", widget: "text"}
              - label: "Feature List"
                name: "feature_list"
                widget: "list"
                fields:
                  - {label: "Feature Title", name: "title", widget: "string"}
                  - {label: "Feature Description", name: "description", widget: "text"}
                  - {label: "Feature Icon", name: "icon", widget: "image"}
